extends Node

# Generated by scripts/gen-gdscript-types.ts
# Phase 0: stub only. Replaced by real bridge protocol codegen later.

const EVT_LOBBY_INIT = "lobby_init"
const EVT_GODOT_READY = "godot_ready"

