/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomIdPlayRouteImport } from './routes/room.$roomId.play'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdPlayRoute = RoomRoomIdPlayRouteImport.update({
  id: '/room/$roomId/play',
  path: '/room/$roomId/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/room/$roomId/play': typeof RoomRoomIdPlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/room/$roomId/play': typeof RoomRoomIdPlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/room/$roomId/play': typeof RoomRoomIdPlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/review' | '/settings' | '/room/$roomId/play'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/review' | '/settings' | '/room/$roomId/play'
  id: '__root__' | '/' | '/review' | '/settings' | '/room/$roomId/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  RoomRoomIdPlayRoute: typeof RoomRoomIdPlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId/play': {
      id: '/room/$roomId/play'
      path: '/room/$roomId/play'
      fullPath: '/room/$roomId/play'
      preLoaderRoute: typeof RoomRoomIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  RoomRoomIdPlayRoute: RoomRoomIdPlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
