import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

/**
 * Phase 0 stub codegen.
 *
 * Later phases should read Zod schemas / event constants from `platform/shared-types`
 * and generate strongly-typed GDScript helpers.
 */
const outPath = join(process.cwd(), 'games', 'tictactoe', 'autoloads', 'BridgeProtocol.gd');
mkdirSync(dirname(outPath), { recursive: true });

const content = `extends Node

# Generated by scripts/gen-gdscript-types.ts
# Phase 0: stub only. Replaced by real bridge protocol codegen later.

const EVT_LOBBY_INIT = "lobby_init"
const EVT_GODOT_READY = "godot_ready"

`;

writeFileSync(outPath, content, 'utf8');
console.log('Wrote', outPath);

